//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMark.Context
{
    using System;

    public partial class tbl_Student
    {
        public int Roll_No { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public int Math { get; set; }
        public int Phy { get; set; }
        public int Chem { get; set; }
        public int Total { get; set; }
        public float Percentage { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public byte[] Updated_date { get; set; }
    }
}
